# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/nick/Escritorio/Proyectos/LabSim/software/LabSim/src/main/python/UI/Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(933, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.layout = QtWidgets.QHBoxLayout()
        self.layout.setContentsMargins(-1, 3, 0, -1)
        self.layout.setObjectName("layout")
        self.frameAction = QtWidgets.QFrame(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.frameAction.setFont(font)
        self.frameAction.setObjectName("frameAction")
        self.layoutTest = QtWidgets.QHBoxLayout(self.frameAction)
        self.layoutTest.setContentsMargins(-1, 0, -1, 0)
        self.layoutTest.setObjectName("layoutTest")
        self.layout.addWidget(self.frameAction)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout.addItem(spacerItem)
        self.layoutAction = QtWidgets.QHBoxLayout()
        self.layoutAction.setContentsMargins(-1, -1, 0, -1)
        self.layoutAction.setObjectName("layoutAction")
        self.layout.addLayout(self.layoutAction)
        self.lbl_name = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lbl_name.setFont(font)
        self.lbl_name.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_name.setObjectName("lbl_name")
        self.layout.addWidget(self.lbl_name)
        self.btn_login = QtWidgets.QPushButton(self.centralwidget)
        self.btn_login.setObjectName("btn_login")
        self.layout.addWidget(self.btn_login)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_min = QtWidgets.QPushButton(self.centralwidget)
        self.btn_min.setMinimumSize(QtCore.QSize(10, 0))
        self.btn_min.setMaximumSize(QtCore.QSize(20, 16777215))
        self.btn_min.setFlat(True)
        self.btn_min.setObjectName("btn_min")
        self.horizontalLayout_2.addWidget(self.btn_min)
        self.btn_max = QtWidgets.QPushButton(self.centralwidget)
        self.btn_max.setMaximumSize(QtCore.QSize(20, 16777215))
        self.btn_max.setFlat(True)
        self.btn_max.setObjectName("btn_max")
        self.horizontalLayout_2.addWidget(self.btn_max)
        self.btn_salir = QtWidgets.QPushButton(self.centralwidget)
        self.btn_salir.setMaximumSize(QtCore.QSize(20, 16777215))
        self.btn_salir.setFlat(True)
        self.btn_salir.setObjectName("btn_salir")
        self.horizontalLayout_2.addWidget(self.btn_salir)
        self.layout.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addLayout(self.layout)
        self.widget_Mdi = QtWidgets.QWidget(self.centralwidget)
        self.widget_Mdi.setObjectName("widget_Mdi")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_Mdi)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.mdiArea = QtWidgets.QMdiArea(self.widget_Mdi)
        self.mdiArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.mdiArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.mdiArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        brush = QtGui.QBrush(QtGui.QColor(136, 142, 147))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.mdiArea.setBackground(brush)
        self.mdiArea.setViewMode(QtWidgets.QMdiArea.SubWindowView)
        self.mdiArea.setDocumentMode(True)
        self.mdiArea.setObjectName("mdiArea")
        self.horizontalLayout.addWidget(self.mdiArea)
        self.verticalLayout.addWidget(self.widget_Mdi)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.statusbar.setFont(font)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLogin = QtWidgets.QAction(MainWindow)
        self.actionLogin.setObjectName("actionLogin")
        self.actionSalir = QtWidgets.QAction(MainWindow)
        self.actionSalir.setObjectName("actionSalir")
        self.actionEnviar_un_ticket = QtWidgets.QAction(MainWindow)
        self.actionEnviar_un_ticket.setObjectName("actionEnviar_un_ticket")
        self.actionAcerca_de = QtWidgets.QAction(MainWindow)
        self.actionAcerca_de.setObjectName("actionAcerca_de")
        self.actionCascada = QtWidgets.QAction(MainWindow)
        self.actionCascada.setObjectName("actionCascada")
        self.actionCerrar_todas = QtWidgets.QAction(MainWindow)
        self.actionCerrar_todas.setObjectName("actionCerrar_todas")
        self.actionTiles = QtWidgets.QAction(MainWindow)
        self.actionTiles.setObjectName("actionTiles")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_name.setText(_translate("MainWindow", "Desconectado"))
        self.btn_login.setText(_translate("MainWindow", "login"))
        self.btn_min.setText(_translate("MainWindow", "_"))
        self.btn_max.setText(_translate("MainWindow", "O"))
        self.btn_salir.setText(_translate("MainWindow", "X"))
        self.actionLogin.setText(_translate("MainWindow", "Ingresar"))
        self.actionSalir.setText(_translate("MainWindow", "Salir"))
        self.actionEnviar_un_ticket.setText(_translate("MainWindow", "Enviar un ticket"))
        self.actionAcerca_de.setText(_translate("MainWindow", "Acerca de LabSim"))
        self.actionCascada.setText(_translate("MainWindow", "Cascada"))
        self.actionCerrar_todas.setText(_translate("MainWindow", "Cerrar todas"))
        self.actionTiles.setText(_translate("MainWindow", "Lozas"))

