# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/nick/Escritorio/Proyectos/LabSim/src/main/python/UI/main_login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainLogin(object):
    def setupUi(self, MainLogin):
        MainLogin.setObjectName("MainLogin")
        MainLogin.resize(664, 170)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainLogin.sizePolicy().hasHeightForWidth())
        MainLogin.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainLogin)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lbl_title = QtWidgets.QLabel(self.centralwidget)
        self.lbl_title.setObjectName("lbl_title")
        self.horizontalLayout_3.addWidget(self.lbl_title)
        self.lbl_status = QtWidgets.QLabel(self.centralwidget)
        self.lbl_status.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lbl_status.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lbl_status.setText("")
        self.lbl_status.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_status.setObjectName("lbl_status")
        self.horizontalLayout_3.addWidget(self.lbl_status)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.name = QtWidgets.QLineEdit(self.centralwidget)
        self.name.setObjectName("name")
        self.horizontalLayout.addWidget(self.name)
        self.passw = QtWidgets.QLineEdit(self.centralwidget)
        self.passw.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passw.setObjectName("passw")
        self.horizontalLayout.addWidget(self.passw)
        self.btn_login = QtWidgets.QPushButton(self.centralwidget)
        self.btn_login.setObjectName("btn_login")
        self.horizontalLayout.addWidget(self.btn_login)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_a = QtWidgets.QPushButton(self.centralwidget)
        self.btn_a.setObjectName("btn_a")
        self.horizontalLayout_2.addWidget(self.btn_a)
        self.btn_z = QtWidgets.QPushButton(self.centralwidget)
        self.btn_z.setObjectName("btn_z")
        self.horizontalLayout_2.addWidget(self.btn_z)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.central_layout = QtWidgets.QVBoxLayout()
        self.central_layout.setObjectName("central_layout")
        self.verticalLayout.addLayout(self.central_layout)
        MainLogin.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainLogin)
        QtCore.QMetaObject.connectSlotsByName(MainLogin)

    def retranslateUi(self, MainLogin):
        _translate = QtCore.QCoreApplication.translate
        MainLogin.setWindowTitle(_translate("MainLogin", "LabSim"))
        self.lbl_title.setText(_translate("MainLogin", "BOX AUDIOLOGÍA"))
        self.btn_login.setText(_translate("MainLogin", "Ingresar"))
        self.btn_a.setText(_translate("MainLogin", "Audiómetro"))
        self.btn_z.setText(_translate("MainLogin", "impedanciómetro"))
