# Form implementation generated from reading ui file '/home/nick/Escritorio/Proyectos/LabSim/software/LabSim/src/main/python/UI/Web_view.ui'
#
# Created by: PySide6 UI code generator 6.2.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_web(object):
    def setupUi(self, web):
        web.setObjectName("web")
        web.resize(400, 300)
        self.horizontalLayout = QtWidgets.QHBoxLayout(web)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.view = QtWebEngineWidgets.QWebEngineView(web)
        self.view.setUrl(QtCore.QUrl("about:blank"))
        self.view.setObjectName("view")
        self.horizontalLayout.addWidget(self.view)

        self.retranslateUi(web)
        QtCore.QMetaObject.connectSlotsByName(web)

    def retranslateUi(self, web):
        _translate = QtCore.QCoreApplication.translate
        web.setWindowTitle(_translate("web", "Form"))
from PySide6 import QtWebEngineWidgets
